# Generated by Django 5.1.4 on 2025-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_description_catagory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='catagory',
            old_name='category_name',
            new_name='catagory_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='catagory_name',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='status',
            field=models.BooleanField(default=False, help_text='0-Show,1-Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
