# Generated by Django 5.1.4 on 2025-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_description_catagory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='status',
            field=models.BooleanField(default=False, help_text='0-Show, 1-Hidden'),
        ),
    ]
