# Generated by Django 5.1.4 on 2025-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
