# Generated by Django 5.1.4 on 2025-01-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catagory_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
